import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { formatExplanation } from "../src/explain.mjs";
import { decide } from "../src/policy.mjs";

test("formats the last routing decision", () => {
  const output = formatExplanation({
    prompt: "Explain the router architecture",
    tier: "sonnet",
    confidence: 0.94,
    reason: "jev",
    model: "claude-sonnet-5",
    jev: {
      // The shape router.mjs actually records: the choice is an exact model id, under `model`.
      request: { state: { session: { current_model: "claude-haiku-4-5", context_tokens: 6200 } } },
      response: { answers: { model: { choice: "claude-sonnet-5" } } },
    },
    metrics: {
      taskComplexity: 0.82,
      reasoningRequired: 0.91,
      toolComplexity: 0.64,
      contextSize: 0.31,
    },
  });

  assert.match(output, /Task complexity     0\.82/);
  assert.match(output, /Prompt: Explain the router/);
  assert.match(output, /Current model: CLAUDE-HAIKU-4-5/);
  assert.match(output, /Context tokens: 6200/);
  // A long model id wraps onto the next row, so the box border sits between the two.
  assert.match(output, /Jev recommended:[\s│]+CLAUDE-SONNET-5/);
  assert.match(output, /Selected model: CLAUDE-SONNET-5/);
  assert.match(output, /Confidence: 94%/);
  assert.match(output, /Decision: Jev recommendation/);
});

test("shows the concrete provider model when available", () => {
  assert.match(
    formatExplanation({ tier: "haiku", model: "gpt-5.6-luna", confidence: 0.99 }),
    /Selected model: GPT-5\.6-LUNA/,
  );
});

test("Claude skill pre-approves its read-only explanation command", () => {
  const skill = readFileSync(new URL("../.claude/skills/jev-explain/SKILL.md", import.meta.url), "utf8");
  assert.match(skill, /^allowed-tools: Bash\(node \*\)$/m);
});

test("representative policy reasons each render their own label", () => {
  // decision() matches substrings of the reason strings policy.mjs produces, so a rename
  // silently falls through to the catch-all. Hardcoding reason strings here would go stale
  // with the renderer and still pass, so the reasons are generated by driving decide() --
  // if a reason is renamed, these cases carry the new name automatically.
  const ALL = ["haiku", "sonnet", "opus", "fable"];
  const cases = {
    override: { prompt: "use haiku", jev: null, current: "opus", available: ALL },
    "jev-unavailable": { prompt: "x", jev: null, current: "opus", available: ALL },
    "low-confidence-no-downgrade": {
      prompt: "x", jev: { choice: "haiku", confidence: 0.1 }, current: "opus", available: ALL,
    },
    "low-confidence-capped": {
      prompt: "x", jev: { choice: "fable", confidence: 0.1 }, current: "haiku", available: ALL,
    },
    "downgrade-confidence-too-low": {
      prompt: "x", jev: { choice: "sonnet", confidence: 0.5 }, current: "opus", available: ALL,
    },
    "+unavailable": {
      prompt: "x", jev: { choice: "sonnet", confidence: 0.95 },
      current: "haiku", available: ["haiku", "opus"],
    },
    jev: { prompt: "x", jev: { choice: "sonnet", confidence: 0.95 }, current: "opus", available: ALL },
  };

  const render = (reason) =>
    formatExplanation({ tier: "opus", model: "claude-opus-5", confidence: 0.9, reason })
      .split("\n")
      .find((l) => l.includes("Decision"))
      .trim();

  const catchAll = render("jev");
  for (const [expected, input] of Object.entries(cases)) {
    const { reason } = decide(input);
    assert(reason.includes(expected), `expected a reason containing ${JSON.stringify(expected)}, got ${JSON.stringify(reason)}`);
    if (expected === "jev") continue;
    assert.notEqual(render(reason), catchAll, `reason ${JSON.stringify(reason)} falls through to the catch-all`);
  }
});

test("a held decision shows the recommendation it refused, not the tier it kept", () => {
  // The whole point of reviewing a blocked downgrade is seeing what was blocked, so the
  // recorded Jev answer has to surface rather than being masked by the selected tier.
  const held = formatExplanation({
    tier: "opus",
    model: "claude-opus-5",
    confidence: 0.5,
    reason: "downgrade-confidence-too-low/no-change",
    jev: { response: { answers: { model: { choice: "claude-sonnet-5" } } } },
  });
  assert(held.includes("CLAUDE-SONNET-5"), "the refused recommendation is not shown");
});
